[package]
name = "othello"
version = "0.1.0"
authors = ["naohiro_oka <shape.a.wonder@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34"
tetra = "0.5"
